ControllerConfig:
  ConnectionString: "amqps://[redacted]]@chimpanzee.rmq.cloudamqp.com/mxgzljbw"
  QueueName: "oem"
  MgtUrl: "http://localhost:15672"
  Port: 8090

EventHubConfig:
  connection: "Endpoint=sb://oem-alarms.servicebus.windows.net/;SharedAccessKeyName=oem-access;SharedAccessKey=[redacted]"
  EventHubName: "oem-alarms"

Duration: 0
LogLevel: 0